trigger:
- main

pool:
  Superman

jobs:
- job: RunNginxJob
  displayName: 'Run Nginx'
  
  steps:
  - checkout: self

  - script: |
      sudo su -
      sudo yum update -y
      sudo yum install nginx -y
      echo "Hello, welcome to Azure Pipeline" > /usr/share/nginx/html/index.html

    displayName: 'Install Nginx'

  - script: |
      sudo service nginx start
    displayName: 'Start Nginx'
