trigger:
- main

pool:
  Superman

jobs:
- job: RunNginxJob
  displayName: 'Run Nginx'
  
  steps:
  - checkout: self

  - script: |
      sudo yum update -y
      sudo amazon-linux-extras install nginx1 -y
    displayName: 'Install Nginx'

  - script: |
      sudo service nginx start
    displayName: 'Start Nginx'
