trigger:
- main

pool:
  Superman

jobs:
- job: RunNginxJob
  displayName: 'Run Nginx'
  
  steps:
  - checkout

  - script: |
      sudo yum update -y
      sudo yum install nginx -y
    displayName: 'Install Nginx'

  - script: |
      sudo service nginx start
    displayName: 'Start Nginx'
