trigger:
- main  # Specify the branch that triggers the pipeline

pool:
  testpool  # Choose an appropriate image based on your requirements

jobs:
- job: RunPythonScript
  displayName: 'Run Python Script'
  
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Specify the Python version you want to use
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt  # If you have any Python package dependencies

  - script: 'python index.py'
    displayName: 'Run Python Script'